# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - juriar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e5ce59993c03461e91483448db28df65 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_02b1c88f478a479da8d5abfcbfa038c5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e5ce59993c03461e91483448db28df65 }}/chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'juriar'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a0a269b1edf949f58efb874272cb43e5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e5ce59993c03461e91483448db28df65 }}/chatbot:${{ github.sha }}'